# Generated by Django 2.0 on 2019-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('MobileNo', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Qualified', models.BooleanField()),
            ],
        ),
    ]
