# Generated by Django 2.0 on 2019-06-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='MobileNo',
            new_name='Mobile_no',
        ),
    ]
